# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "arm64-apple-ios17.0-simulator" -Xcc "-isysroot" -Xcc "`xcrun --sdk iphonesimulator --show-sdk-path`"
    - name: Test
      run: xcodebuild test -scheme OnboardingiOSSDK -destination 'platform=iOS Simulator,name=iPhone 14' -sdk iphonesimulator
      continue-on-error: true
